In [1]:
import tensorflow as tf
import numpy as np

timesteps = 1

# e.g (三筆，字詞向量長度假設5)
train_data = [[0,0,1,0,1],
              [1,0,0,0,1],
              [0,0,1,0,1],
              [1,1,0,0,1]]
num_input = len(train_data[0])
# 輸入資料為二維[未知筆數，字詞向量長度]
inputX = tf.placeholder("float", [None, num_input])

# 三維格式
# (未知筆數，每筆輸入次數，輸入的屬性數量)
X = tf.placeholder("float", [None, timesteps, num_input])

# 將二維轉換為三維
# -1，是自動計算剩餘大小來得出最後size
# 例：二維 3 * 5，叁維x*1*5，3*5 = ?*1*5 => ? = 3
reshapeX = tf.reshape(inputX, (-1, timesteps, num_input))

# 轉換為numpy類型
npdata = np.array(train_data,np.int32) 

with tf.Session() as sess:
    print(sess.run(reshapeX, feed_dict={inputX: npdata}))

[[[ 0.  0.  1.  0.  1.]]

 [[ 1.  0.  0.  0.  1.]]

 [[ 0.  0.  1.  0.  1.]]

 [[ 1.  1.  0.  0.  1.]]]


In [3]:
np.arange(6).reshape(3, -1)

array([[0, 1],
       [2, 3],
       [4, 5]])